# Generated by Django 2.2.1 on 2019-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerAppName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(help_text='APPkey', max_length=64, unique=True, verbose_name='APPkey')),
                ('app_name', models.CharField(help_text='APP名称', max_length=32, verbose_name='APP名称')),
                ('app_desc', models.CharField(help_text='APP应用描述', max_length=32, verbose_name='APP应用描述')),
            ],
            options={
                'db_table': 'pms_app',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='权限简称', max_length=32, verbose_name='权限简称')),
                ('desc', models.CharField(help_text='权限描述信息', max_length=32, verbose_name='权限描述信息')),
                ('groups', models.ManyToManyField(help_text='用户组关联权限', related_name='pms_group', to='auth.Group', verbose_name='用户组关联权限')),
            ],
            options={
                'db_table': 'pms_permission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(db_index=True, help_text='service名称', max_length=32, verbose_name='节点名称')),
                ('pid', models.IntegerField(db_index=True, help_text='pid', verbose_name='节点pid')),
                ('path_node', models.CharField(db_index=True, help_text='node中文path', max_length=32, verbose_name='节点中文path')),
                ('groups', models.ManyToManyField(help_text='用户组关联节点', related_name='node_group', to='auth.Group', verbose_name='用户组关联节点')),
            ],
            options={
                'db_table': 'pms_node',
                'ordering': ['id'],
            },
        ),
    ]
