# Generated by Django 2.2.1 on 2019-07-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perappname',
            old_name='app_desc',
            new_name='appdesc',
        ),
    ]
