# Generated by Django 2.2.1 on 2019-07-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_auto_20190702_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perappname',
            old_name='appdesc',
            new_name='app_desc',
        ),
        migrations.RenameField(
            model_name='perappname',
            old_name='appkey',
            new_name='app_key',
        ),
        migrations.RenameField(
            model_name='perappname',
            old_name='appname',
            new_name='app_name',
        ),
    ]
